export const ACCOUNT_ACTIVATE = 'ACCOUNT_ACTIVATE'
export const TYPE_VIP_ACCOUNT = 'TYPE_VIP_ACCOUNT'

export const ACCOUNT_VIP_0 = 'ACCOUNT_VIP_0'
export const ACCOUNT_VIP_1 = 'ACCOUNT_VIP_1'
export const ACCOUNT_VIP_2 = 'ACCOUNT_VIP_2'
export const ACCOUNT_VIP_3 = 'ACCOUNT_VIP_3'